mutation {
    createTest(
        testType: { name: "Generic" },
        unstructured: "Automated Test",
        jira: {
            fields: { summary: "%SUMMARY_NAME%", project: {key: "AUT"} }
        }
    ) {
        test {
            issueId
            testType {
                name
            }
            unstructured
            jira(fields: ["key"])
        }
        warnings
    }
}
