mutation {
    createTestPlan(
        testIssueIds: []
        jira: {
            fields: {
                summary: "%SUMMARY_NAME%",
                project: {key: "AUT"}
            }
        }
    ) {
        testPlan {
            issueId
            jira(fields: ["key"])
        }
        warnings
    }
}